### ISSUE TITLE
GAN evaluation metrics

### ISSUE THREAD

**Issue by ghost** [hahahappyboy/GAN-Thesis-Retrieval#1]
Hi,

This is an interesting collection of GANs. I have already tried two SPADE and Pix2PixHD.
I was wondering what evaluation methods you have used to evaluate the GAN models?
If you have used an evaluation metric, can you please provide the steps on how to do that

Thank you

**Comment by hahahappyboy** [comment]
Thank you for your question
For image translation tasks, I usually use FID, MS-SSIM, LPIPS.
I don't know exactly how they work, you can read about them in related papers, but this link summarizes how to use them.
https://blog.csdn.net/iiiiiiimp/article/details/123946075?spm=1001.2014.3001.5501

**Comment by ghost** [comment]
Thank you so much that was helpful.
You have perfectly summarized them.

**Comment by hahahappyboy** [comment]
My pleasure.
