### ISSUE TITLE
Visualizing the loss_log

### ISSUE THREAD

**Issue by ghost** [hahahappyboy/GAN-Thesis-Retrieval#2]
I was wondering if you have a script that plots the loss_log.txt into a graph?
I did not do it while training so I want to visualize them after. 

Thank you again

**Comment by hahahappyboy** [comment]
I don't have such a script. you might be able to use Tensorboard.

**Comment by ghost** [comment]
I thought Tensorboard can be used while training. I will check that thank you.

**Comment by hahahappyboy** [comment]
My pleasure.
